### ISSUE TITLE
Make configuration more accessible

### ISSUE THREAD

**Issue by cherryman** [MariHacks/quill#1]
Much of the configuration is done by editing files within `/app`. Ideally, this configuration should be closer to the root, and ideally hardcoded constants should be deploy specific. The following changes are necessary:

- [x] `app/client/assets` should be at the root, perhaps as `assets`.
- [x] Branding colours are in `app/client/stylesheets/_custom.scss`, and then imported in `site.scss`. These should be moved to a `colours.scss` at the root or in a `config/` dir. This can be done by deleting `app/client/stylesheets/_{branding,custom}.scss` files and replacing the first two imports in `site.scss` accordingly.
- [x]  Several hardcoded values of MITHacks, do a global search for `mithack`, find all instances, and _unhardcode_ them, preferably configuration through `.env` using `process.env.VARIABLE_NAME`
- [x] Photo release form should preferably be served from `/assets` as well.

**Comment by thematrixmaster** [comment]
assets folder was moved to root.
app/server was successfully moved to root.
app/client was deleted and its items were all moved to root.
photo release form was downloaded and placed in the assets folder. It is now being served from this location.
env variables were added for HACK_NAME and HACK_YEAR. Instances of HackMIT and 2015 were replaced using process.env in all .js files. However, instances of HackMIT and 2015 were manually replaced with MariHacks 2020 in all HTML and JADE files because I could not find a way to replace them with env variables.
